# Generated by Django 3.1.7 on 2021-03-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='cite_key',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
