# Generated by Django 3.1.7 on 2021-03-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sok', '0002_auto_20210311_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='references_complete',
        ),
    ]
